CREATE DATABASE contact_book;

CREATE TABLE department
(
    id   INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) UNIQUE NOT NULL
);

CREATE TABLE "role"
(
    id            INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name          VARCHAR(100) UNIQUE NOT NULL,
    readable_name VARCHAR(100) UNIQUE NOT NULL
);

CREATE TABLE "account"
(
    id         INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    login      VARCHAR(50)  NOT NULL UNIQUE,
    password   VARCHAR      NOT NULL,
    role       VARCHAR,
    name       VARCHAR(100) NOT NULL,
    surname    VARCHAR(100) NOT NULL,
    patronymic VARCHAR(100),
    department INT          REFERENCES department (id) ON DELETE SET NULL
);

CREATE TABLE role_user
(
    user_id INT REFERENCES "account" (id) ON DELETE CASCADE,
    role_id INT REFERENCES "role" (id) ON DELETE CASCADE,
    PRIMARY KEY (user_id, role_id)
);

CREATE TABLE contact
(
    id           INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    contact_name VARCHAR NOT NULL,
    creator_id   INT     REFERENCES "account" ON DELETE SET NULL
);

CREATE TABLE contact_details
(
    id          INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    for_contact INT REFERENCES contact (id) ON DELETE CASCADE NOT NULL,
    details     VARCHAR                                       NOT NULL,
    type        VARCHAR
);

CREATE TABLE label
(
    id   INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR UNIQUE
);

CREATE TABLE contact_label
(
    contact_id INT REFERENCES contact (id) ON DELETE CASCADE NOT NULL,
    label_id   INT REFERENCES label (id) ON DELETE CASCADE   NOT NULL,
    PRIMARY KEY (contact_id, label_id)
);

CREATE TABLE note
(
    id          INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    text        VARCHAR                                       NOT NULL,
    for_contact INT REFERENCES contact (id) ON DELETE CASCADE NOT NULL
);

CREATE TABLE "group"
(
    id      INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name    VARCHAR NOT NULL UNIQUE,
    creator INT     REFERENCES "account" (id) ON DELETE SET NULL
);

CREATE TABLE read_permission
(
    group_id INT REFERENCES "group" (id) ON DELETE CASCADE   NOT NULL,
    user_id  INT REFERENCES "account" (id) ON DELETE CASCADE NOT NULL,
    PRIMARY KEY (group_id, user_id)
);

CREATE TABLE write_permission
(
    group_id INT REFERENCES "group" (id) ON DELETE CASCADE   NOT NULL,
    user_id  INT REFERENCES "account" (id) ON DELETE CASCADE NOT NULL,
    PRIMARY KEY (group_id, user_id)
);

INSERT INTO role (name, readable_name)
VALUES ('ROLE_USER', 'Пользователь'),
       ('ROLE_ADMIN', 'Администратор');

ALTER TABLE account
    DROP COLUMN role;